[package]
name = "graph_jpr"
version = "0.1.1"
edition = "2021"

[lib]
name = "graph_jpr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
numpy = "0.20.0"
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["intel-mkl"] }